spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/foodfrenzydb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:indra06}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=${PORT:8080}